# Generated by Django 3.1.4 on 2020-12-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_chats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
    ]
